spring:
  application:
    name: networkdisk-user
  config:
    import: classpath:datasource.yml,classpath:cache.yml,classpath:rpc.yml
server:
  port: 8085

#dubbo:
#  protocol:
#    port: 20889
#  application:
#    qos-port: 33333
