spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #首次启动前务必修改成你自己的
      config:
        server-addr: 127.0.0.1:8848 #首次启动前务必修改成你自己的
        file-extension: properties
        name: ${spring.application.name}